format = """
$time $username in $directory $all"""

[cmd_duration]
min_time = 500
format = "[\\($duration spent\\)](bright-black)"

[directory]
format = "[$path/]($style)[$read_only]($read_only_style)"
style = "cyan"

[git_branch]
style = "bright-black"

[git_status]
style = "bright-black"

[time]
disabled = false
format = '[\[$time\]]($style)'
style = 'white'

[username]
style_user = "bright-blue"
style_root = "red"
format = "[$user]($style)"
show_always = true