format = """
$time $username in $directory $all"""

[cmd_duration]
min_time = 500
format = "[\\($duration spent\\)](bright-black)"

[directory]
format = "[$path/]($style)[$read_only]($read_only_style)"
style = "cyan"
read_only = " ro"

[git_commit]
tag_symbol = " tag "

[git_branch]
style = "bright-black"
symbol = "git "

[git_status]
style = "bright-black"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[time]
disabled = false
format = '[\[$time\]]($style)'
style = 'white'

[username]
style_user = "bright-blue"
style_root = "red"
format = "[$user]($style)"
show_always = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

# Language-specific

[aws]
symbol = "aws "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "